import { jsPDF } from "jspdf";
import "jspdf-autotable";

export const generateProjectReport = () => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Title
  doc.setFontSize(24);
  doc.setTextColor(0, 0, 0);
  doc.text("PROJECT REPORT: UNIVO AI", pageWidth / 2, 20, { align: "center" });

  // Subtitle
  doc.setFontSize(14);
  doc.setTextColor(100, 100, 100);
  doc.text("AI Assistant for MEA Engineering College", pageWidth / 2, 30, { align: "center" });

  // Line
  doc.setLineWidth(0.5);
  doc.line(20, 35, pageWidth - 20, 35);

  // Section: Introduction
  doc.setFontSize(16);
  doc.setTextColor(0, 0, 0);
  doc.text("1. Introduction", 20, 50);
  doc.setFontSize(11);
  doc.setTextColor(50, 50, 50);
  const introText = "Univo AI is a modern, AI-powered student assistant designed specifically for MEA Engineering College. It provides instant answers about admissions, class schedules, events, and campus services, helping students navigate college life more efficiently.";
  const splitIntro = doc.splitTextToSize(introText, pageWidth - 40);
  doc.text(splitIntro, 20, 60);

  // Section: Technology Stack
  doc.setFontSize(16);
  doc.setTextColor(0, 0, 0);
  doc.text("2. Technology Stack", 20, 85);
  
  const techData = [
    ["Category", "Technology Used"],
    ["Frontend Framework", "React (TypeScript)"],
    ["Styling", "Tailwind CSS"],
    ["AI Model", "Google Gemini API (gemini-3-flash-preview)"],
    ["Animations", "Framer Motion"],
    ["Icons", "Lucide React"],
    ["Build Tool", "Vite"],
    ["Deployment", "Vercel / Cloud Run"]
  ];

  (doc as any).autoTable({
    startY: 95,
    head: [techData[0]],
    body: techData.slice(1),
    theme: 'striped',
    headStyles: { fillColor: [190, 242, 100], textColor: [0, 0, 0] },
  });

  // Section: Core Features
  const finalY = (doc as any).lastAutoTable.finalY || 150;
  doc.setFontSize(16);
  doc.setTextColor(0, 0, 0);
  doc.text("3. Core Features", 20, finalY + 20);
  
  doc.setFontSize(11);
  doc.setTextColor(50, 50, 50);
  const features = [
    "• Admissions Help: Instant info about procedures and deadlines.",
    "• Timetable Access: Real-time class and exam schedules.",
    "• Student Records: Access to marks and attendance via Student ID.",
    "• Campus Events: Stay updated with seminars and cultural fests.",
    "• 24/7 Support: AI-powered help available anytime."
  ];
  doc.text(features, 20, finalY + 30);

  // Section: How It Works
  doc.setFontSize(16);
  doc.setTextColor(0, 0, 0);
  doc.text("4. How It Works", 20, finalY + 70);
  
  const howItWorks = "The application uses a custom-trained system prompt containing comprehensive college datasets. When a user asks a question, the Google Gemini AI processes the query against this dataset and generates a relevant, formatted response in real-time.";
  const splitHow = doc.splitTextToSize(howItWorks, pageWidth - 40);
  doc.text(splitHow, 20, finalY + 80);

  // Footer
  doc.setFontSize(10);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by Univo AI Platform - 2026", pageWidth / 2, 285, { align: "center" });

  // Save the PDF
  doc.save("Univo_Project_Report.pdf");
};
